ARG NODE_VERSION=10
FROM debian:10-slim

# Home directory for Node-RED application source code.
 RUN mkdir -p /usr/src/node-red

# User data directory, contains flows, config and nodes.
 RUN mkdir /data

 WORKDIR /usr/src/node-red

# Add node-red user so we aren't running as root.
 RUN adduser --home /usr/src/node-red --disabled-password --no-create-home --gecos  "" node-red \
     && chown -R node-red:node-red /data \
         && chown -R node-red:node-red /usr/src/node-red

 RUN  apt-get update && apt-get install npm net-tools -y
 USER node-red

 # package.json contains Node-RED NPM module and node dependencies
 COPY package.json /usr/src/node-red/
 RUN npm install

 # User configuration directory volume
 VOLUME ["/data"]
 EXPOSE 1880

 # Environment variable holding file path for flows configuration
 ENV FLOWS=flows.json

 CMD ["npm", "start", "--", "--userDir", "/data"]

